cstrike.wad
gfx/env/forestbk.tga
gfx/env/forestdn.tga
gfx/env/forestft.tga
gfx/env/forestlf.tga
gfx/env/forestrt.tga
gfx/env/forestup.tga
halflife.wad
liquids.wad
models/apache.mdl
models/bigrat.mdl
models/bskull_template1.mdl
models/uplant1.mdl
models/uplant2.mdl
sound/ambience/alienwind1.wav
sound/ambience/biggun1.wav
sound/ambience/biggun2.wav
sound/ambience/cicada3.wav
sound/ambience/crickets.wav
sound/ambience/crow.wav
sound/ambience/deadsignal2.wav
sound/ambience/fallscream.wav
sound/ambience/flies.wav
sound/ambience/kajika.wav
sound/ambience/quail1.wav
sound/ambience/ratchant.wav
sound/ambience/sparrow.wav
sound/ambience/waterfall3.wav
sound/apache/ap_rotor4.wav
sound/bullchicken/bc_pain2.wav
sound/buttons/latchlocked1.wav
sprites/fire.spr
sprites/muzzleflash2.spr
sprites/nhth1.spr
sprites/stmbal1.spr
sprites/wsplash3.spr
